name: Build UWP Package
on:
  push:
    branches:
      - uwp
  pull_request:
    branches:
      - uwp

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Set up NuGet
      uses: NuGet/setup-nuget@v2

    - name: Extract version string from AppxManifest
      id: extract_version
      run: |
        $manifest = [xml](Get-Content pcsx2-winrt\Package.appxmanifest)
        $version = $manifest.Package.Identity.Version
        echo $version
        echo version=$version >> $env:GITHUB_OUTPUT
        
    - name: Echo the GitHub Env for File Names
      run: |
       echo "${{ steps.extract_version.outputs.version }}"
    
    - name: Restore NuGet packages
      run: nuget restore PCSX2_qt.sln

    - name: Build the project
      run: msbuild PCSX2_qt.sln /t:Restore,Rebuild /p:Configuration=Release /p:Platform=x64
  
    - name: Build APPX
      run: |
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/makeappx.exe' encrypt /p AppPackages\xbsx2\xbsx2_${{ steps.extract_version.outputs.version }}_x64_Test\xbsx2_${{ steps.extract_version.outputs.version }}_x64.appx /ep "xbsx2_${{ steps.extract_version.outputs.version }}.eappx" /kt
   
    - name: Upload unencrypted APPX
      uses: actions/upload-artifact@v4
      with:
        name: unencrypted-appx
        path: "AppPackages\\xbsx2_${{ steps.extract_version.outputs.version }}_x64_Test\\XboxLinux_${{ steps.extract_version.outputs.version }}_x64.appx"

    - name: Upload encrypted APPX
      uses: actions/upload-artifact@v4
      with:
        name: encrypted-appx
        path: "xbsx2_${{ steps.extract_version.outputs.version }}.eappx"
